name: Self-Approve Author PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  auto_approve:
    if: github.actor == 'jacekchmiel'

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Generate Token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Approve PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            const { owner, repo, number: pull_number } = context.issue;

            // Check if pull_number is valid
            if (!pull_number) {
              console.error('Error: Could not retrieve Pull Request number.');
              return;
            }

            if (context.payload.pull_request.user.login === 'jacekchmiel') {
              github.rest.pulls.createReview({
                owner,
                repo,
                pull_number,
                event: 'APPROVE',
                body: 'Auto-approved by auto-approve-bot for the PR author.'
              });
              console.log('Successfully approved the pull request.');
            } else {
              console.log('PR author does not match the configured user. Skipping auto-approval.');
            }