name: Rust

on:
  push:
    branches: ["main"]
    paths:
      - src-tauri/**
      - package.json
      - .github/workflows/rust.yml
  pull_request:
    branches: ["main"]
    paths:
      - src-tauri/**
      - package.json
      - .github/workflows/rust.yml

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev
          version: 1.0
      - uses: Swatinem/rust-cache@v2
      - name: Check
        working-directory: ./src-tauri
        run: cargo check --verbose
      - name: Build tests
        working-directory: ./src-tauri
        run: cargo build --workspace --tests
      - name: Run tests
        working-directory: ./src-tauri
        run: cargo test --workspace --verbose
