name: Typescript

on:
  push:
    branches: ["main"]
    paths:
        - ui/**
  pull_request:
    branches: ["main"]
    paths:
        - ui/**
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ui
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: install frontend dependencies
      run: npm install
    - name: check
      run: npm run check
    - name: test
      run: npm run test
    - name: build
      run: npm run build